updated CI/CD for automatic plugin upload

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,145 +1,196 @@
-# Automatically build multi-architectural tagged container images and push them to DockerHub
-# https://github.com/FNNDSC/cookiecutter-chrisapp/wiki/Automatic-Builds
+# Continuous integration testing for ChRIS Plugin.
+# https://github.com/FNNDSC/python-chrisapp-template/wiki/Continuous-Integration
 #
-# - targeted platforms: x86_64, PowerPC64, ARM64
-# - master is built as fnndsc/pl-lld_inference:latest
-# - tagged commits are built as fnndsc/pl-lld_inference:<tag>
-# - tagged commits are also uploaded to chrisstore.co
-#
-# In order to use this workflow, see
-# https://github.com/FNNDSC/cookiecutter-chrisapp/wiki/Automatic-Builds#steps-to-enable
+# - on push and PR: run pytest
+# - on push to main: build and push container images as ":latest"
+# - on push to semver tag: build and push container image with tag and
+#                          upload plugin description to https://chrisstore.co
 
-name: ci
+name: build
 
 on:
   push:
-    # we have to guess what the name of the default branch is
-    branches: [ master, main, trunk ]
-    tags: [ '**' ]
+    branches: [ main ]
+    tags:
+      - "v?[0-9]+.[0-9]+.[0-9]+*"
   pull_request:
-    branches: [ master, main, trunk ]
+    branches: [ main ]
 
 jobs:
   test:
-    if: false
-    runs-on: ubuntu-20.04
+    name: Unit tests
+    if: False
+    runs-on: ubuntu-22.04
     steps:
-      - uses: actions/checkout@v2
-      - name: build
-        run: docker build -t "${GITHUB_REPOSITORY,,}" .
-      - name: nose tests
-        run: docker run "${GITHUB_REPOSITORY,,}" nosetests
+      - uses: actions/checkout@v4
+      - uses: docker/setup-buildx-action@v3
+      - name: Build
+        uses: docker/build-push-action@v5
+        with:
+          build-args: extras_require=dev
+          context: .
+          load: true
+          push: false
+          tags: "localhost/local/app:dev"
+          cache-from: type=gha
+          cache-to: type=gha,mode=max
+      - name: Run pytest
+        run: |
+          docker run -v "$GITHUB_WORKSPACE:/app:ro" -w /app localhost/local/app:dev \
+            pytest -o cache_dir=/tmp/pytest
 
-  publish:
+  build:
+    name: Build
     if: github.event_name == 'push' || github.event_name == 'release'
+    # needs: [ test ]  # uncomment to require passing tests
     runs-on: ubuntu-22.04
 
-    # we want to both push the build to DockerHub, but also
-    # keep a local copy so that we can run
-    #
-    #     docker run fnndsc/pl-app app --json > App.json
-    #
-    # buildx currently does not support multiple output locations,
-    # neither can multi-architectural builds be loaded into docker.
-    # Here we use a local registry to cache the build.
-    services:
-      registry:
-        image: registry:2
-        ports:
-          - 5000:5000
-
     steps:
-      - name: Get git tag
-        id: git_info
-        if: startsWith(github.ref, 'refs/tags/')
-        run: echo "tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
-      - name: Get project info
-        id: determine
-        env:
-          git_tag: ${{ steps.git_info.outputs.tag }}
+      - name: Decide image tags
+        id: info
+        shell: python
         run: |
-          repo="${GITHUB_REPOSITORY,,}"  # to lower case
-          # if build triggered by tag, use tag name
-          tag="${git_tag:-latest}"
-          dock_image=$repo:$tag
-          echo $dock_image
-          echo "dock_image=$dock_image" >> $GITHUB_OUTPUT
-          echo "repo=$repo" >> $GITHUB_OUTPUT
+          import os
+          import itertools
 
-      - uses: actions/checkout@v3
+          def join_tag(t):
+            registry, repo, tag = t
+            return f'{registry}/{repo}:{tag}'.lower()
+
+          registries = ['docker.io', 'ghcr.io']
+          repos = ['${{ github.repository }}']
+          if '${{ github.ref_type }}' == 'branch':
+              tags = ['latest']
+          elif '${{ github.ref_type }}' == 'tag':
+              tag = '${{ github.ref_name }}'
+              version = tag[1:] if tag.startswith('v') else tag
+              tags = ['latest', version]
+          else:
+              tags = []
+
+          if '${{ github.ref_type }}' == 'tag':
+              local_tag = join_tag(('ghcr.io', '${{ github.repository }}', version))
+          else:
+              local_tag = join_tag(('localhost', '${{ github.repository }}', 'latest'))
+
+          product = itertools.product(registries, repos, tags)
+          tags_csv = ','.join(map(join_tag, product))
+          outputs = {
+              'tags_csv' : tags_csv,
+              'push'     : 'true' if tags_csv else 'false',
+              'local_tag': local_tag
+          }
+          with open(os.environ['GITHUB_OUTPUT'], 'a') as out:
+              for k, v in outputs.items():
+                  out.write(f'{k}={v}\n')
+
+      - uses: actions/checkout@v4
         # QEMU is used for non-x86_64 builds
-      - uses: docker/setup-qemu-action@v2
+      - uses: docker/setup-qemu-action@v3
         # buildx adds additional features to docker build
-      - uses: docker/setup-buildx-action@v2
+      - uses: docker/setup-buildx-action@v3
         with:
           driver-opts: network=host
-        # cache slightly improves rebuild time
-      - name: Cache Docker layers
-        uses: actions/cache@v3
-        with:
-          path: /tmp/.buildx-cache
-          key: ${{ runner.os }}-buildx-${{ github.sha }}
-          restore-keys: |
-            ${{ runner.os }}-buildx-
 
-      - name: Login to DockerHub
-        id: dockerhub_login
-        uses: docker/login-action@v2
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_PASSWORD }}
-          
-      - name: Login to GitHub Container Registry
-        uses: docker/login-action@v2
-        with:
-          registry: ghcr.io
-          username: ${{ github.repository_owner }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Build and push
+        # Here, we want to do the docker build twice:
+        # The first build pushes to our local registry for testing.
+        # The second build pushes to Docker Hub and ghcr.io
+      - name: Build (local only)
         uses: docker/build-push-action@v3
         id: docker_build
         with:
           context: .
           file: ./Dockerfile
-          tags: |
-            localhost:5000/${{ steps.determine.outputs.dock_image }}
-            docker.io/${{ steps.determine.outputs.dock_image }}
-            ghcr.io/${{ steps.determine.outputs.dock_image }}
-          platforms: linux/amd64
-          push: true
-          cache-from: type=local,src=/tmp/.buildx-cache
-          cache-to: type=local,dest=/tmp/.buildx-cache
+          tags: ${{ steps.info.outputs.local_tag }}
+          load: true
+          cache-from: type=gha
+      # If you have a directory called examples/incoming/ and examples/outgoing/, then
+      # run your ChRIS plugin with no parameters, and assert that it creates all the files
+      # which are expected. File contents are not compared.
+      - name: Run examples
+        id: run_examples
+        run: |
+          if ! [ -d 'examples/incoming/' ] || ! [ -d 'examples/outgoing/' ]; then
+            echo "No examples."
+            exit 0
+          fi
+        
+          dock_image=${{ steps.info.outputs.local_tag }}
+          output_dir=$(mktemp -d)
+          cmd=$(docker image inspect -f '{{ (index .Config.Cmd 0) }}' $dock_image)
+          docker run --rm -u "$(id -u):$(id -g)" \
+            -v "$PWD/examples/incoming:/incoming:ro" \
+            -v "$output_dir:/outgoing:rw" \
+            $dock_image $cmd /incoming /outgoing
+          
+          for expected_file in $(find examples/outgoing -type f); do
+            fname="${expected_file##*/}"
+            out_path="$output_dir/$fname"
+            printf "Checking output %s exists..." "$out_path"
+            if [ -f "$out_path" ]; then
+              echo "ok"
+            else
+              echo "not found"
+              exit 1
+            fi
+          done
+
+      - name: Login to DockerHub
+        if: (github.event_name == 'push' || github.event_name == 'release') && contains(steps.info.outputs.tags_csv, 'docker.io')
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_PASSWORD }}
+      - name: Login to GitHub Container Registry
+        if: (github.event_name == 'push' || github.event_name == 'release') && contains(steps.info.outputs.tags_csv, 'ghcr.io')
+        uses: docker/login-action@v3
+        with:
+          registry: ghcr.io
+          username: ${{ github.repository_owner }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+      - name: Build and push
+        uses: docker/build-push-action@v5
+        if: (github.event_name == 'push' || github.event_name == 'release')
+        with:
+          context: .
+          file: ./Dockerfile
+          tags: ${{ steps.info.outputs.tags_csv }}
+          # if non-x86_84 architectures are supported, add them here
+          platforms: linux/amd64  #,linux/arm64,linux/ppc64le
+          push: ${{ steps.info.outputs.push }}
+          cache-to: type=gha,mode=max
 
       - name: Get plugin meta
         id: pluginmeta
         run: |
-          repo=${{ steps.determine.outputs.repo }}
-          dock_image=${{ steps.determine.outputs.dock_image }}
-          docker pull localhost:5000/$dock_image
-          docker tag localhost:5000/$dock_image $dock_image
-          script=$(docker inspect --format '{{ (index .Config.Cmd 0) }}' $dock_image)
-          docker run --rm $dock_image $script --json > /tmp/description.json
+            repo=${{ steps.determine.outputs.repo }}
+            dock_image=${{ steps.determine.outputs.dock_image }}
+            docker pull localhost:5000/$dock_image
+            docker tag localhost:5000/$dock_image $dock_image
+            script=$(docker inspect --format '{{ (index .Config.Cmd 0) }}' $dock_image)
+            json="$(docker run --rm $dock_image $script --json)"
+            jq <<< "$json"  # pretty print in log
+            
+            echo "::set-output name=json::$json"
+            echo "::set-output name=title::$(jq -r '.title' <<< "$json")"
 
-          jq < /tmp/description.json  # pretty print in log
-          echo "title=$(jq -r '.title' < /tmp/description.json)" >> $GITHUB_OUTPUT
+      - name: Upload ChRIS Plugin
+        id: upload
+        if: github.ref_type == 'tag'
+        uses: FNNDSC/upload-chris-plugin@v1
+        with:
+          description_json: ${{ steps.pluginmeta.outputs.json }}
+          username: ${{ secrets.CHRISPROJECT_USERNAME }}
+          password: ${{ secrets.CHRISPROJECT_PASSWORD }}
+          chris_url: https://cube.chrisproject.org/api/v1/
+          compute_names: NERC
 
       - name: Update DockerHub description
+        if: steps.upload.outcome == 'success'
         uses: peter-evans/dockerhub-description@v3
         continue-on-error: true  # it is not crucial that this works
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_PASSWORD }}
-          short-description: ${{ steps.pluginmeta.outputs.title }}
-          readme-filepath: ./README.rst
-          repository: ${{ steps.determine.outputs.repo }}
-
-      - name: Upload to ChRIS Store
-        if: steps.git_info.outcome != 'skipped'
-        uses: FNNDSC/chrisstore-action@master
-        with:
-          descriptor_file: /tmp/description.json
-          auth: ${{ secrets.CHRIS_STORE_USER }}
-          chris_admin_auth: ${{ secrets.CUBE_CHRISPROJECT_ORG_ADMIN_USER }}
-          chris_admin_url: https://cube.chrisproject.org/chris-admin/api/v1/
-          compute_resources: galena-avx
+          short-description: ${{ steps.upload.outputs.title }}
+          readme-filepath: ./README.md
